# Generated by Django 3.1.2 on 2021-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_category_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='spending',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='支出'),
        ),
    ]
